LED_protocol:

  colors: # All triplets should be ordered [R,G,B]
    switchedoff: [0,0,0]
    white: [1,1,1]
    green: [0,1,0]
    red: [1,0,0]
    light_red: [0.2,0,0]
    blue: [0,0,1]
    yellow: [1,0.8,0]
    purple: [1,0,1]
    cyan: [0,1,1]
    pink: [1,0,0.5]
    orange: [1,0.3,0]

  frequencies:
    f1: &f1 1.9
    f2: &f2 4
    f3: &f3 5.7
    f4: &f4 7.8
    f5: &f5 10.6
    f6: &f6 0.5

  signals:
    CAR_SIGNAL_PRIORITY:
      color_mask: []
      color_list: ["purple","red","purple","red","purple"]
      frequency_mask: [1,0,1,0,1]
      frequency: *f3

    CAR_SIGNAL_SACRIFICE_FOR_PRIORITY:
      color_mask: []
      color_list: ["white","red","white","red","white"]
      frequency_mask: [1,0,1,0,1]
      frequency: *f1

    CAR_SIGNAL_A:
      color_mask: []
      color_list: ["white","red","white","red","white"]
      frequency_mask: [1,0,1,0,1]
      frequency: *f2

    CAR_SIGNAL_GREEN:
      color_mask: []
      color_list: "green"
      frequency_mask: [1,1,1,1,1]
      frequency: *f3

    CAR_DRIVING:
      color_mask: []
      color_list: ["white","light_red","white","switchedoff","light_red"]
      frequency_mask: []
      frequency:  0

    CAR_STOP:
      color_mask: []
      color_list: ["white","red","white","switchedoff","red"]
      frequency_mask: []
      frequency:  0

    CAR_TURN_LEFT:
      color_mask: []
      color_list: ["orange","light_red","white","switchedoff","orange"]
      frequency_mask: [1,0,0,0,1]
      frequency:  *f6

    WHITE:
      color_mask: []
      color_list: "white"
      frequency_mask: []
      frequency:  0

    RED:
      color_mask: []
      color_list: "red"
      frequency_mask: []
      frequency:  0

    GREEN:
      color_mask: []
      color_list: "green"
      frequency_mask: []
      frequency:  0

    BLUE:
      color_mask: []
      color_list: "blue"
      frequency_mask: []
      frequency:  0
      
    YELLOW:
      color_mask: []
      color_list: "yellow"
      frequency_mask: []
      frequency:  0

    ORANGE:
      color_mask: []
      color_list: "orange"
      frequency_mask: []
      frequency:  0

    LIGHT_OFF:
      color_mask: []
      color_list: "switchedoff"
      frequency_mask: []
      frequency:  0

    light_off:
      color_mask: []
      color_list: "switchedoff"
      frequency_mask: []
      frequency:  0

    OBSTACLE_ALERT:
      color_mask: []
      color_list: ["white","yellow","white","yellow","white"]
      frequency_mask: [0,1,0,1,0]
      frequency:  *f1

    OBSTACLE_STOPPED:
      color_mask: []
      color_list: ["white","red","white","red","white"]
      frequency_mask: [0,1,0,1,0]
      frequency:  *f2

    POPO:
      color_mask: []
      color_list: ["blue","red","switchedoff","blue","red"]
      frequency_mask: [1,1,0,1,1]
      frequency: *f2

    CAR_TEST_1:
      color_mask: []
      color_list: ["red","switchedoff","switchedoff","switchedoff","switchedoff"]
      frequency_mask: []
      frequency:  0

    CAR_TEST_2:
      color_mask: []
      color_list: ["switchedoff","red","switchedoff","switchedoff","switchedoff"]
      frequency_mask: []
      frequency:  0

    CAR_TEST_3:
      color_mask: []
      color_list: ["switchedoff","switchedoff","red","switchedoff","switchedoff"]
      frequency_mask: []
      frequency:  0

    CAR_TEST_4:
      color_mask: []
      color_list: ["switchedoff","switchedoff","switchedoff","red","switchedoff"]
      frequency_mask: []
      frequency:  0

    CAR_TEST_5:
      color_mask: []
      color_list: ["switchedoff","switchedoff","switchedoff","switchedoff","red"]
      frequency_mask: []
      frequency:  0

LED_scale: 0.8
channel_order:
  duckiebot: "RGB"
  traffic_light: "GRB"
