turn_parameters: {
  v_max     : 0.7,
  omega_max : 8,
  steps     : 10
}

search_area : {
  top     : 360,
  bottom  : 400
}

turn_values: {
  forward_speed: {
    v       : 0.4,
    omega   : 0,
    time    : 4
  },
  left_turn: {
    v       : 0.3,
    radius  : 0.34,
    time    : 4,
    steps   : 3
  },
  right_turn: {
    v       : 0.3,
    radius  : 0.13,
    time    : 4,
    steps   : 3
  },
  short_forward_speed: {
    v       : 0.3,
    omega   : 0,
    time    : 2
  }
}